//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.15 at 02:46:54 PM CDT 
//


package trng.imcs.beans;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Student complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Student"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="StudentId" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="StudentFirstName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="StudentLastName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="StudentAddress" type="{http://www.example.org/Address}Address" maxOccurs="unbounded"/&gt;
 *         &lt;element name="StudentMarks" type="{http://www.example.org/Marks}Marks" maxOccurs="unbounded"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Student", namespace = "http://www.example.org/Student", propOrder = {
    "studentId",
    "studentFirstName",
    "studentLastName",
    "studentAddress",
    "studentMarks"
})
public class Student {

    @XmlElement(name = "StudentId")
    protected int studentId;
    @XmlElement(name = "StudentFirstName", required = true)
    protected String studentFirstName;
    @XmlElement(name = "StudentLastName", required = true)
    protected String studentLastName;
    @XmlElement(name = "StudentAddress", required = true)
    protected List<Address> studentAddress;
    @XmlElement(name = "StudentMarks", required = true)
    protected List<Marks> studentMarks;
    
    

    public Student() {
		super();
	}

	public Student(int studentId, String studentFirstName, String studentLastName, List<Address> studentAddress,
			List<Marks> studentMarks) {
		super();
		this.studentId = studentId;
		this.studentFirstName = studentFirstName;
		this.studentLastName = studentLastName;
		this.studentAddress = studentAddress;
		this.studentMarks = studentMarks;
	}

	/**
     * Gets the value of the studentId property.
     * 
     */
    public int getStudentId() {
        return studentId;
    }

    /**
     * Sets the value of the studentId property.
     * 
     */
    public void setStudentId(int value) {
        this.studentId = value;
    }

    /**
     * Gets the value of the studentFirstName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStudentFirstName() {
        return studentFirstName;
    }

    /**
     * Sets the value of the studentFirstName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStudentFirstName(String value) {
        this.studentFirstName = value;
    }

    /**
     * Gets the value of the studentLastName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStudentLastName() {
        return studentLastName;
    }

    /**
     * Sets the value of the studentLastName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStudentLastName(String value) {
        this.studentLastName = value;
    }

    /**
     * Gets the value of the studentAddress property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the studentAddress property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStudentAddress().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Address }
     * 
     * 
     */
    public List<Address> getStudentAddress() {
        if (studentAddress == null) {
            studentAddress = new ArrayList<Address>();
        }
        return this.studentAddress;
    }

    /**
     * Gets the value of the studentMarks property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the studentMarks property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStudentMarks().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Marks }
     * 
     * 
     */
    public List<Marks> getStudentMarks() {
        if (studentMarks == null) {
            studentMarks = new ArrayList<Marks>();
        }
        return this.studentMarks;
    }

}
